"""empty message

Revision ID: 7d9a44794f9a
Revises: 
Create Date: 2024-05-03 13:56:35.919721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9a44794f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_dimension',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('act_req_dimension',
    sa.Column('act_req_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('act_req_id')
    )
    op.create_table('comment_dimension',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('ingredient_dimension',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('recipe_dimension',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('combined_fact_table',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_dimension.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_dimension.recipe_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_fact_table')
    op.drop_table('recipe_dimension')
    op.drop_table('ingredient_dimension')
    op.drop_table('comment_dimension')
    op.drop_table('act_req_dimension')
    op.drop_table('account_dimension')
    # ### end Alembic commands ###
