"""empty message

Revision ID: 9c71e6b3610e
Revises: 7d9a44794f9a
Create Date: 2024-05-04 17:38:30.096501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c71e6b3610e'
down_revision = '7d9a44794f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('act_req_dimension')
    with op.batch_alter_table('comment_dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_comment_dimension_user_id', 'account_dimension', ['user_id'], ['user_id'])
        batch_op.drop_column('username')

    with op.batch_alter_table('recipe_dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_dimension_user_id', 'account_dimension', ['user_id'], ['user_id'])
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_comment_dimension_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comment_dimension', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_account_dimension_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('act_req_dimension',
    sa.Column('act_req_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('act_req_id')
    )
    # ### end Alembic commands ###
